### PR TITLE
Add set color method

### PR DESCRIPTION
**Pull request by tcqq**
Solve #234 problem

add method:

setEmojiViewBackgroundColor
setVariantPopupBackgroundColor
setEmojiViewIconNormalColor
setEmojiViewIconSelectedColor
setVariantIndicatorColor
setDividerColor

### CODE REVIEW

**Comment by TCQQ** [comment]
Screenshots
image
image

**Comment by vanniktech** [comment]
Sorry for not getting back earlier to this.

Why aren't you overriding the resources?

**Comment by vanniktech** [comment]
You completely reformatted everything which I definitely don't want.

In the library those resources are defined.

Emoji library:

```xml
<resources>
    <color name="emoji_background">#eceff1</color>
    <color name="emoji_icons">#61000000</color>
    <color name="emoji_divider">#1f000000</color>
</resources>
```

In your app you can just override them

```xml
<resources>
    <color name="emoji_background">#ff0000</color>
    <color name="emoji_icons">#00ff00</color>
    <color name="emoji_divider">#0000ff</color>
</resources>
```

That way I don't need to update the library with methods that are not needed and you can get the solution straight away.

**Comment by tcqq** [comment]
Yes, but if the application's theme color allows the user to pass a color code, this situation will have to programmatically change the color, because it is impossible to write all the color values in style.

**Comment by vanniktech** [comment]
I'm still thinking what's the best way to have your wanted functionality.

**Comment by tcqq** [comment]
Change color programmatically, instead of changing the color through xml, because this can support any color switching.

**Comment by vanniktech** [comment]
In case you want to continue this, please start from fresh.

**Comment by tcqq** [comment]
@vanniktech What is “fresh”? Code easier to create?

**Comment by vanniktech** [comment]
The minimal changes - without reformatting the entire code - in a new PR.

**Comment by tcqq** [comment]
## This is my code now, So all styles need only be configured once
Activity：image
image

**Comment by hvar90** [comment]
hi
i want to change the color of category selected 
you said before is possible override resources
```
<resources>
    <color name="emoji_background">#ff0000</color>
    <color name="emoji_icons">#00ff00</color>
    <color name="emoji_divider">#0000ff</color>
</resources>
```
but there is no way to change the selected category color 
the only way is changing colorAccent global color but i want a specific color for the color of category selected 

how could i do that ?

**Pull request closed without merging**
