### PR TITLE
Don't use bundled AppCompat emojis. Instead download the font.

### PR DESCRIPTION
**Pull request by vanniktech**
Much much better. Thanks to @stefanhaustein for providing the integration with Google's AppCompat.

### CODE REVIEW

**Comment by mario** [comment]
Cool, but where are these certs from?

**Comment by vanniktech** [comment]
Google sample's everyone is using 'em.

**Comment by mario** [comment]
Generally saying I'm more for bundled option (privacy related), but oh well. Looks good otherwise.

**Comment by vanniktech** [comment]
It's the sample app and everyone is showing how to use the bundled one so I'm for the font one. In general, people can choose what they want since we support both options.

**Pull request merged**
