### PR TITLE
fix keyboard with customize keyboard

### PR DESCRIPTION
**Pull request by chihung93**
Customize for fixing emoji on some specialist devices

### CODE REVIEW

**Comment by vanniktech** [comment]
Thanks for starting to work on this. Can anyone who's gotten the issue from #191 verify that this does fix the issue as I can't reproduce? @daniele-athome @danielgaribaldi @186538

**Comment by daniele-athome** [comment]
I could try with [my user's way of reproducing the issue](https://github.com/kontalk/androidclient/issues/1110#issuecomment-348548271). I'll let you know. Thanks @chihung93!

**Comment by vanniktech** [comment]
@daniele-athome any news?

**Comment by daniele-athome** [comment]
Sorry for being late. I've been testing the sample app, the close-keyboard-before-showing-emoji mechanism works, but there is something wrong with the detection of the keyboard height, so the EditText moves up and down between keyboard and emojis. I might do something to fix that (I already do it in my code), but I have a couple of questions:

* EditText cursor disappears because the view loses focus (it shouldn't lose it. Right?)
* I guess the keyboard height is not handled automatically by your view but it has to be provided via setKeyboardHeight
* AFAICU the emoji panel is hidden when the EditText is clicked. I feel like it's wrong. OnClick might not be the only event that triggers the keyboard (what about OnFocus? Or anything else)

I feel I can somehow contribute to this, but I can't promise anything on short term. Anyway I'll have to work on this sooner or later :-)

**Comment by vanniktech** [comment]
Regarding your first question yes.
Yeah custom keyboard height needs to be considered. We might even need to special case the notch on some devices.
OnFocus like selecting the text should also dismiss it. 

Thanks for picking this up in the future!

**Comment by vanniktech** [comment]
This is super old now and in a state on which we can't advance further. Hence I'm closing this but willing to reconsider once the PR reaches a mergeable state.

**Pull request closed without merging**
