### PR TITLE
Add emoji toolbar

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by vanniktech** [comment]
Maybe the solution is to ship a LayoutFactorty that replaces all TextView's by our TextView's. That would handle all cases with custom views etc.

**Comment by mario** [comment]
@vanniktech my use case was simple so this is what I did. The long term solution is different of course :)

**Comment by vanniktech** [comment]
Let me think about this a bit more

**Comment by mario** [comment]
I think a factory is actually a nice idea.

**Comment by rubengees** [comment]
If we do it like this, it should be a module on it's own, because it pulls in `material-components` which is large.

**Comment by vanniktech** [comment]
> If we do it like this, it should be a module on it's own, because it pulls in `material-components` which is large.

Yup that's for sure!

I'm more inclined to provide a custom LayoutFactory though and then it'll just work _everywhere_

**Pull request closed without merging**
