### PR TITLE
EmojiPopUp: RequestApplyInsets

### LINKED ISSUE #439: Emoji popup coming above the keyboard
- Version of the library: 0.6.0
- Affected devices: Pixel 3a XL Emulator

Screenshot_1588788391

### PR DESCRIPTION
**Pull request by ghshenavar**
I didn't find the exact situation that caused the bug but I found another one that almost always caused a bug for me : if I opened the app then opened the dialog and clicked on the emoji button then came back to main activity and clicked the emoji button the keyboard size and or place was wrong.
picture is taken from the emulator Pixel 3a XL API 30:
Screenshot_1592743200
This is how I fixed the issue on my device.

### CODE REVIEW

**Comment by vanniktech** [comment]
Thanks for your contribution!

**Comment by drmkraja** [comment]
@vanniktech I'm also facing this Issue... Can I get this update in 0.7.0-SNAPSHOT or you release a stable version ?

**Comment by vanniktech** [comment]
Yes use 0.7.0-SNAPSHOT for now.

**Comment by vanniktech** [comment]
Or build the aar locally and include via mavenLocal / custom nexus repository - which is what I'm doing.

**Review by Pandastacos — COMMENTED** [review]
Needed this

**Pull request merged**
