### PR TITLE
Allow to pass in selectedIconColor.

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by mario** [comment]
Uh, cool enough, but can you please isolate changes when doing future PRs? Otherwise it makes it tricky for me to review :-/

**Comment by vanniktech** [comment]
What would you like to be splitted?

**Comment by mario** [comment]
Well, there were lots of changed NOT related to selectedIconColor :)

**Comment by vanniktech** [comment]
Didn't feel like adding another int when I can just pass around the builder ;)

**Pull request merged**
