### PR TITLE
Update README license

### PR DESCRIPTION
**Pull request by mario**

### CODE REVIEW

**Comment by mario** [comment]
Well, your copyright extends from day 1 to current day. So why not add this? If you look at the bottom left of this very site, it says 2019, not the day they started :)

**Comment by rubengees** [comment]
See my comment here: https://github.com/vanniktech/Emoji/issues/331

**Comment by vanniktech** [comment]
Don't forget to change the value in `gradle.properties`.

**Comment by vanniktech** [comment]
@mario want to pursue this further?

**Comment by mario** [comment]
Yes @vanniktech, I even assigned a milestone :P It'll just take me a bit of time.

**Comment by vanniktech** [comment]
How about we just do:

```
Copyright (C) 2016 Vanniktech - Niklas Baudy and contributors
```

?

**Comment by vanniktech** [comment]
We can also include both of your names. I was just suggesting to cut the `- 2019`

**Comment by mario** [comment]
You need to include every year or a range at least :)

**Comment by vanniktech** [comment]
Square isn't providing a range either and I like to stick with what they do.

**Comment by rubengees** [comment]
I am fine either way.

**Comment by mario** [comment]
@rubengees and @vanniktech - updated. Merge or change as desired.

**Comment by vanniktech** [comment]
Waiting for @rubengees approval

**Pull request merged**
