### PR TITLE
Keep file to keep sheets which are accessed through reflection.

### LINKED ISSUE #533: Proguard removes emojis with isShrinkResources=true
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: **0.8.0**
- Affected devices:
99% HUAWEI
<1% Xiaomi

`Fatal Exception: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
       at android.graphics.Bitmap.createBitmap(Bitmap.java:998)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:958)
       at com.vanniktech.emoji.google.GoogleEmoji.getDrawable(GoogleEmoji.java:41)
       at com.vanniktech.emoji.EmojiSpan.getDrawable(EmojiSpan.java:8)
       at com.vanniktech.emoji.EmojiSpan.draw(EmojiSpan.java)
       at android.text.TextLine.handleReplacement(TextLine.java:1020)
       at android.text.TextLine.handleRun(TextLine.java:1167)
       at android.text.TextLine.drawRun(TextLine.java:500)
       at android.text.TextLine.draw(TextLine.java:289)
       at android.text.Layout.drawText(Layout.java:576)
       at android.text.Layout.draw(Layout.java:324)
       at android.widget.TextView.onDraw(TextView.java:8060)`

This happens because of proguard

`Skipped unused resource res/drawable-nodpi-v4/emoji_google_sheet_52.png: 39406 bytes (replaced with small dummy file of size 67 bytes)`

Fixed with file raw/keep.xml with folowing content:
`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/emoji_*" />
`
----------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #533

### CODE REVIEW

**Comment by vanniktech** [comment]
Anyone @mario / @rubengees ?

**Review by rubengees — APPROVED** [review]
I don't really do Android development currently so I'm not up the latest things, but isn't this more of a proguard/current_shrinking_tool bug than us missing these files? Because now the drawables won't be removed if they are unused e.g. when a user depends on the library without actively using it or other edge cases.

Nevertheless if this helps it's a good change I think.

**Comment by mario** [comment]
Will check tonight.

**Comment by vanniktech** [comment]
We do use reflection to get these and there's no way that R8/Proguard can now this; hence we should keep it since we know we use it and also need it.

**Pull request merged**
