### PR TITLE
Add support to AutoCompleteTextView and MultiAutoCompleteTextView

### PR DESCRIPTION
**Pull request by rocboronat**
This PR just adds `EmojiAutoCompleteTextView` implementation. It's just a copypaste of the `EditText` class, but extending `AutoCompleteTextView` and using the new `attrs.xml` values.

BTW, as the project is not building right now, I didn't try it. When we fix it, I'll try it in the sample project.

Let's talk about it on #291

### CODE REVIEW

**Comment by rocboronat** [comment]
@vanniktech feel free to ignore this PR till I notify you. Consider it a work in progress, just to showcase my progress... if we can consider it "progress", hehe!

**Comment by vanniktech** [comment]
Is this ready now?

**Comment by rocboronat** [comment]
@vanniktech if you like the approach I did to test both widgets, yes, it's ready to go. But I think we should remove the new Activities, because they exists only to test the new widgets, and didn't give too much value... What you think? If you like them, feel free to merge, and if not, I will remove last commit.

**Comment by rocboronat** [comment]
Hey @vanniktech, do you have any thoughts about my answer?

**Comment by rocboronat** [comment]
No problem, I'm happy to contribute to the project 😇

**Pull request merged**
