### PR TITLE
RecentEmojiManager: Increase max emoji count to 100.

### PR DESCRIPTION
**Pull request by vanniktech**
40 might be too low.

### CODE REVIEW

**Comment by mario** [comment]
Might be too low compared to what? XD

**Comment by vanniktech** [comment]
:100:

**Comment by vanniktech** [comment]
Sure we can make it configurable. I'd still like a default of 100

**Comment by mario** [comment]
Ok, make it configurable with max 100 and then I'll approve this :P

**Comment by rubengees** [comment]
I looked at other emoji pickers and all seem to have around 40 in their recent grids. Why do you plan to increase that? I wouldn't have anything against configuration though.

Telegram: 40
WhatsApp: 36
Slack: 21

**Comment by mario** [comment]
Though I guess it's already possible to do that by providing your own RecentEmojiManager?

**Comment by vanniktech** [comment]
Let's leave at 40 then

**Pull request closed without merging**
