### PR TITLE
Create Height Offset

### PR DESCRIPTION
**Pull request by searchy2**
*Create Emoji Builder method to add height offset to EmojiPopup.

### CODE REVIEW

**Comment by searchy2** [comment]
Apologies for the reformatting.

**Comment by searchy2** [comment]
Is this the appropriate style? https://github.com/square/java-code-styles
I am having some trouble applying it. Importing into Android Studio does not seem to work.

**Comment by vanniktech** [comment]
Yup it is.

**Comment by searchy2** [comment]
`Intellij IDEA code style XML import failed with error message: Can't read fromSquareAndroid.xml, Error on line 42: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.`

This is the error I'm getting when trying to import. Can you fix the indentations instead?

**Comment by vanniktech** [comment]
I'm not even sure I want this property as I said.

**Comment by searchy2** [comment]
It would be useful in cases like mine where the only way to get proper layouting is to add a manual offset. Otherwise, there is no easy way to fix the gap.

**Comment by vanniktech** [comment]
My problem is that this hides the underlying problem (Dialog height calculated wrong in the first place). Can you check whether if you enable immersive mode in the sample app you get the same behavior / bug?

**Comment by searchy2** [comment]
The problem is that there is no problem haha. In immersive mode, the sample app calculates the height of the keyboard correctly. Your code works perfectly! :+1: 

I have attempted to isolate the cause of the issue in my app but have been unable to do so. Again, there is nothing wrong with your library. In my app, I find the offset is the same value (after dp->px) on every device so an offset would fix the issue for me.

**Comment by vanniktech** [comment]
I'll close this then since it's a problem on your end and I don't want to burden the API of this library with this extra method that others may get confused about. Also you should try to fix the problem on your side rather than proposing a solution to every library that will be hit by this.

Another idea might be that `fitSystemWindows` is responsible for that effect.

**Pull request closed without merging**
