### PR TITLE
Multiplatform: Add iOS target.

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by Caij** [comment]
https://github.com/cketti/kotlin-codepoints

**Comment by vanniktech** [comment]
Yes I saw it but last time I checked, they don't have a constructor for the code points on string, or am I overseeing something?

**Comment by cketti** [comment]
You can use `StringBuilder.appendCodePoint()` to build a string from a list of code points.

I'm also happy to add a helper function to the library. Maybe something like this?

```kotlin
fun stringFromCodePoints(vararg codePoints: Int): String {
    val charCount = codePoints.sumOf { CodePoints.charCount(it) }
    return buildString(capacity = charCount) {
        for (codePoint in codePoints) {
            appendCodePoint(codePoint)
        }
    }
}
```

**Comment by vanniktech** [comment]
I'm following your library and yes I think https://github.com/cketti/kotlin-codepoints/pull/40 would unblock this.

**Comment by cketti** [comment]
The functionality is available via `CodePoints.toString(…)` in `de.cketti.unicode:kotlin-codepoints:0.9.0`. The API isn't particularly stable, though. You probably want to wrap the library call with your own function so you don't have to change a lot of places should the name of the library function change in a future release.

**Pull request merged**
