### PR TITLE
Add copyright headers

### PR DESCRIPTION
**Pull request by mario**
The lazy approach. But better than what we have now.

### CODE REVIEW

**Comment by mario** [comment]
Depends on my previous PR merged.

**Comment by mario** [comment]
Rebased.

**Comment by vanniktech** [comment]
@mario You would have less work if you would branch your PR's always from a fresh master :D

**Comment by mario** [comment]
With this particular PR you are right - with others, not so much as they either depend on each other or it's easier for me to wrap my head around a particular issue when other surrounding issues are solved :)

**Comment by vanniktech** [comment]
@mario needs a rebase. Also, all of the other files that we've added since the creation of this PR are missing. Let's wait until we've merged all PR's and proceed with this one?

**Comment by mario** [comment]
Yup, absolutely.

**Comment by vanniktech** [comment]
Let's just start from fresh. Too many conflicts and too stale.

**Pull request closed without merging**
