### PR TITLE
Update generator for new data source version

### PR DESCRIPTION
**Pull request by rubengees**
With this, we can generate the code and images for the latest emoji standard. The change also comes with some general updates to other dependencies and the infrastrucutre.

After this is merged, I can open another PR with the generated code (already tried locally, looks good so far).

### CODE REVIEW

**Review by vanniktech — COMMENTED** [review]
Amazing, let's do it!

**Review by vanniktech — APPROVED** [review]

**Comment by vanniktech** [comment]
@rubengees you can merge yourself right?

**Comment by mario** [comment]
Let me check this out please in a day or two.

**Comment by vanniktech** [comment]
@mario sure most of the changes is the lock file. Other than that just a few code changes and some more dependency updates. The real change comes when re-generating all files

**Comment by vanniktech** [comment]
@mario gentle reminder :)

**Pull request merged**
