### PR TITLE
Optimise the category png's to save some space

### PR DESCRIPTION
**Pull request by rocboronat**
This PR is related to the conversation we had on #366.

So, the category images have been optimised with ImageOptim, and it saved about 31% per file on average. That's about 4KB per project! Wow. Huge change.

### CODE REVIEW

**Comment by rocboronat** [comment]
Wow, according to GitHub, the compression is between 65% and 75%. That's even more! 😂

**Comment by rocboronat** [comment]
@vanniktech done! I totally missed that pictures 👍

**Comment by rocboronat** [comment]
🎉

**Comment by vanniktech** [comment]
Thanks for your contribution!

**Comment by rocboronat** [comment]
My pleasure. It's not a big one, but I was wondering which files I could strip from my app, and just thought what could happen if I optimise this lib's pics. Thanks for your work @vanniktech @rubengees 😄

**Pull request merged**
