### PR TITLE
Add shortcodes to emojis

### PR DESCRIPTION
**Pull request by rubengees**
This adds a new field with the shortcode to the `Emoji` class. Accordingly the generator has been extended.

This does not implement any UI or herlper methods yet.

### CODE REVIEW

**Comment by mario** [comment]
Isn't a shortcode supposed to be prefixed with ":" ?

**Comment by vanniktech** [comment]
Also how does slack know that `ant` could also be `bug` when I'm typing `bu`?

Screenshot 2020-06-02 at 13 24 40

**Comment by mario** [comment]
Slack is wrong because an ant is not a bug xD

**Comment by rubengees** [comment]
@vanniktech You're right, there can actually be more (and our datasource has them)! I'll change it so we have a `List<String>` there.

@mario The ":" prefix is a markup convention which is used to detect emojis in text. It's not part of any standard I think.

**Comment by vanniktech** [comment]
Thanks @rubengees 🙏

**Pull request merged**
