### PR TITLE
Add sample with custom view.

### PR DESCRIPTION
**Pull request by vanniktech**
This does work with 95e0c8ee but not with ee9b8ebb

### CODE REVIEW

**Comment by mario** [comment]
Fixed.

**Comment by mario** [comment]
I merged my emoji filter branch + additional commit to fix stuff.

**Comment by mario** [comment]
What do we do here?

**Comment by mario** [comment]
@vanniktech can you rebase so we can merge? :)

**Comment by vanniktech** [comment]
@mario `adjustResize` is broken though. Custom view + adjustResize does not work. How come?

**Comment by mario** [comment]
I will check. I use adjust resize all the time.

**Comment by vanniktech** [comment]
@mario ready for a review. Have you had time to look into adjustResize?

**Comment by vanniktech** [comment]
Found a way to break it:


ezgif com-video-to-gif

**Comment by mario** [comment]
@vanniktech can you check it out now pls?

**Comment by vanniktech** [comment]
Indeed @mario. I've tweaked it so that the custom view contains all of the views / popup.

**Comment by mario** [comment]
@rubengees can you check this out and merge if you agree? :) Otherwise I'll merge in a week. Thanks!

**Comment by mario** [comment]
@vanniktech what's up with travis here? Stuck?

**Comment by vanniktech** [comment]
Yeah. Seems like it

**Comment by mario** [comment]
I can't merge since I am not an admin...

**Pull request merged**
